apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx  
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
          - name: web-http 
            containerPort: 80
          env:
          - name: TESTE_ENV
            value: OK
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '50m'
              memory: '100Mi'
            requests:
              cpu: '10m'
              memory: '50Mi'
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5        