apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: nginx-app
spec:
  containers:
    - name: nginx
      image: nginx:stable
      ports:
      - name: web 
        containerPort: 80 
      env:
      - name: TESTE_ENV
        value: OK        
      imagePullPolicy: Always
      resources:
        limits:
          cpu: '100m'
          memory: '500Mi'
        requests:
          cpu: '100m'
          memory: '500Mi'      
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5          
