apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx-app
spec:
  type: ClusterIP
  selector:
    app: nginx 
  ports:
  - name: web-http 
    protocol: TCP
    port: 80
    targetPort: web-http    